version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PHP_ENV=development
      - PHP_DISPLAY_ERRORS=Off
      - PHP_LOG_ERRORS=On
    volumes:
      - ./Images/PaymentSlips:/var/www/html/Images/PaymentSlips
      - ./Images/PrescriptionMessage:/var/www/html/Images/PrescriptionMessage
      - ./Images/PrescriptionOrders:/var/www/html/Images/PrescriptionOrders
      - ./Images/Profile_Pics:/var/www/html/Images/Profile_Pics
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: pharmaxapp-network
